"""Create Student model

Revision ID: e250f5b4b6cf
Revises: 91c635f5566d
Create Date: 2025-02-06 17:23:07.532349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e250f5b4b6cf'
down_revision = '91c635f5566d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_attendance')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('teacher',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('roll_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.create_foreign_key(None, 'student', ['roll_number'], ['roll_number'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('roll_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('roll_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('roll_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('teacher',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('_alembic_tmp_attendance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), nullable=False),
    sa.Column('teacher', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('roll_number', sa.INTEGER(), nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['roll_number'], ['student.roll_number'], name='fk_attendance_student'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
